package services

import "errors"

var (
	ErrInvalidCredentials                          = errors.New("services: invalid credentials")
	ErrInvalidRefreshToken                         = errors.New("services: invalid refresh token")
	ErrDatasetNotFound                             = errors.New("services: dataset not found")
	ErrInvalidDatasetKey                           = errors.New("services: invalid dataset key")
	ErrInvalidDatasetGroup                         = errors.New("services: invalid dataset group")
	ErrInvalidPagination                           = errors.New("services: invalid pagination")
	ErrUsernameUnavailable                         = errors.New("services: username unavailable")
	ErrEmailUnavailable                            = errors.New("services: email unavailable")
	ErrAccountNotFound                             = errors.New("services: account not found")
	ErrCurrentPasswordInvalid                      = errors.New("services: current password invalid")
	ErrAccountInactive                             = errors.New("services: account inactive")
	ErrAPIKeyNotFound                              = errors.New("services: api key not found")
	ErrAPIKeyNameRequired                          = errors.New("services: api key name is required")
	ErrAPIKeyLimitReached                          = errors.New("services: api key limit reached")
	ErrInvalidUsagePeriod                          = errors.New("services: invalid usage period")
	ErrStateNotFound                               = errors.New("services: state not found")
	ErrInvalidStateID                              = errors.New("services: invalid state id")
	ErrGeopoliticalZoneNotFound                    = errors.New("services: geopolitical zone not found")
	ErrInvalidGeopoliticalZoneID                   = errors.New("services: invalid geopolitical zone id")
	ErrPaymentServiceProviderNotFound              = errors.New("services: payment service provider not found")
	ErrInvalidPaymentServiceProviderID             = errors.New("services: invalid payment service provider id")
	ErrInvalidPaymentServiceProviderType           = errors.New("services: invalid payment service provider type")
	ErrLocalGovernmentUnitNotFound                 = errors.New("services: local government unit not found")
	ErrInvalidLocalGovernmentUnitID                = errors.New("services: invalid local government unit id")
	ErrLanguageNotFound                            = errors.New("services: language not found")
	ErrInvalidLanguageID                           = errors.New("services: invalid language id")
	ErrInvalidCountryLanguageCountryAreaID         = errors.New("services: invalid country language country area id")
	ErrInvalidCountryLanguageLanguageID            = errors.New("services: invalid country language language id")
	ErrInvalidCountryLanguageStatus                = errors.New("services: invalid country language status")
	ErrTimeZoneNotFound                            = errors.New("services: time zone not found")
	ErrInvalidTimeZoneID                           = errors.New("services: invalid time zone id")
	ErrInvalidTimeZoneCountryAreaID                = errors.New("services: invalid time zone country area id")
	ErrCountryOrAreaNotFound                       = errors.New("services: country or area not found")
	ErrInvalidCountryOrAreaID                      = errors.New("services: invalid country or area id")
	ErrInvalidCountryOrAreaRegionCode              = errors.New("services: invalid country or area region code")
	ErrInvalidCountryOrAreaSubregionCode           = errors.New("services: invalid country or area subregion code")
	ErrUniversityNotFound                          = errors.New("services: university not found")
	ErrInvalidUniversityID                         = errors.New("services: invalid university id")
	ErrInvalidUniversityOwnershipType              = errors.New("services: invalid university ownership type")
	ErrInvalidUniversityStateID                    = errors.New("services: invalid university state id")
	ErrCollegeOfEducationNotFound                  = errors.New("services: college of education not found")
	ErrInvalidCollegeOfEducationID                 = errors.New("services: invalid college of education id")
	ErrInvalidCollegeOfEducationOwnershipType      = errors.New("services: invalid college of education ownership type")
	ErrInvalidCollegeOfEducationStateID            = errors.New("services: invalid college of education state id")
	ErrInternationalMoneyTransferOperatorNotFound  = errors.New("services: international money transfer operator not found")
	ErrInvalidInternationalMoneyTransferOperatorID = errors.New("services: invalid international money transfer operator id")
	ErrCurrencyNotFound                            = errors.New("services: currency not found")
	ErrInvalidCurrencyID                           = errors.New("services: invalid currency id")
	ErrInvalidCurrencyCountryAreaID                = errors.New("services: invalid currency country area id")
	ErrCommercialBankNotFound                      = errors.New("services: commercial bank not found")
	ErrInvalidCommercialBankID                     = errors.New("services: invalid commercial bank id")
)
