// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (
    username,
    email,
    password_hash,
    status,
    email_verified_at,
    last_login_at
) VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, 'active'),
    $5,
    $6
)
RETURNING id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Username        string             `json:"username"`
	Email           pgtype.Text        `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Column4         interface{}        `json:"column_4"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
}

// Accounts queries
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Column4,
		arg.EmailVerifiedAt,
		arg.LastLoginAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM accounts
WHERE lower(email) = lower($1)
  AND email IS NOT NULL
  AND deleted_at IS NULL
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM accounts
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM accounts
WHERE lower(username) = lower($1)
  AND deleted_at IS NULL
`

func (q *Queries) GetAccountByUsername(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM accounts
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsAfter = `-- name: ListAccountsAfter :many
SELECT id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
FROM accounts
WHERE deleted_at IS NULL
  AND (
    created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListAccountsAfterParams struct {
	Limit     int32              `json:"limit"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) ListAccountsAfter(ctx context.Context, arg ListAccountsAfterParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsAfter, arg.Limit, arg.CreatedAt, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountLogin = `-- name: MarkAccountLogin :one
UPDATE accounts
SET
    last_login_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

func (q *Queries) MarkAccountLogin(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, markAccountLogin, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :one
UPDATE accounts
SET
    status = 'deleted',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, softDeleteAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :one
UPDATE accounts
SET
    password_hash = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateAccountPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountPassword, arg.ID, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE accounts
SET
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateAccountProfileParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile, arg.ID, arg.Username, arg.Email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyAccountEmail = `-- name: VerifyAccountEmail :one
UPDATE accounts
SET
    email_verified_at = COALESCE(email_verified_at, now()),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, username, email, password_hash, status, email_verified_at, last_login_at, created_at, updated_at, deleted_at
`

func (q *Queries) VerifyAccountEmail(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, verifyAccountEmail, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
