// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAPIKeysByAccountID = `-- name: CountActiveAPIKeysByAccountID :one
SELECT COUNT(*)::bigint AS active_count
FROM api_keys
WHERE account_id = $1
  AND status = 'active'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) CountActiveAPIKeysByAccountID(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeysByAccountID, accountID)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    account_id,
    name,
    key_prefix,
    key_hash,
    key_last4,
    status,
    last_used_at,
    expires_at,
    revoked_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, 'active'),
    $7,
    $8,
    $9
)
RETURNING id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	AccountID  pgtype.UUID        `json:"account_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	KeyLast4   string             `json:"key_last4"`
	Column6    interface{}        `json:"column_6"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

// API keys queries
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.AccountID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.KeyLast4,
		arg.Column6,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredAPIKeys = `-- name: DeleteExpiredAPIKeys :exec
DELETE FROM api_keys
WHERE expires_at IS NOT NULL
  AND expires_at < now()
`

func (q *Queries) DeleteExpiredAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAPIKeys)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
FROM api_keys
WHERE key_prefix = $1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByAccountID = `-- name: ListAPIKeysByAccountID :many
SELECT id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
FROM api_keys
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAPIKeysByAccountIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListAPIKeysByAccountID(ctx context.Context, arg ListAPIKeysByAccountIDParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.KeyLast4,
			&i.Status,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByAccountIDAfter = `-- name: ListAPIKeysByAccountIDAfter :many
SELECT id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
FROM api_keys
WHERE account_id = $1
  AND (
    created_at < $3
    OR (created_at = $3 AND id < $4)
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAPIKeysByAccountIDAfterParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Limit     int32              `json:"limit"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) ListAPIKeysByAccountIDAfter(ctx context.Context, arg ListAPIKeysByAccountIDAfterParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByAccountIDAfter,
		arg.AccountID,
		arg.Limit,
		arg.CreatedAt,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.KeyLast4,
			&i.Status,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET
    status = 'revoked',
    revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND status <> 'revoked'
RETURNING id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rotateAPIKey = `-- name: RotateAPIKey :one
UPDATE api_keys
SET
    status = 'revoked',
    revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND status <> 'revoked'
RETURNING id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
`

func (q *Queries) RotateAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, rotateAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :one
UPDATE api_keys
SET
    last_used_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, account_id, name, key_prefix, key_hash, key_last4, status, last_used_at, expires_at, revoked_at, created_at, updated_at
`

func (q *Queries) TouchAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, touchAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.KeyLast4,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
