// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              pgtype.UUID        `json:"id"`
	Username        string             `json:"username"`
	Email           pgtype.Text        `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	AccountID  pgtype.UUID        `json:"account_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	KeyLast4   string             `json:"key_last4"`
	Status     string             `json:"status"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ApiRequest struct {
	ID             int64              `json:"id"`
	RequestID      string             `json:"request_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	ApiKeyID       pgtype.UUID        `json:"api_key_id"`
	AnonymousID    pgtype.UUID        `json:"anonymous_id"`
	Method         string             `json:"method"`
	Path           string             `json:"path"`
	Route          pgtype.Text        `json:"route"`
	QueryParams    []byte             `json:"query_params"`
	StatusCode     int32              `json:"status_code"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	ResponseTimeMs pgtype.Int4        `json:"response_time_ms"`
	RequestBytes   pgtype.Int8        `json:"request_bytes"`
	ResponseBytes  pgtype.Int8        `json:"response_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DatasetGroup   pgtype.Text        `json:"dataset_group"`
}

type Dataset struct {
	ID              pgtype.UUID        `json:"id"`
	DatasetKey      string             `json:"dataset_key"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	GroupName       string             `json:"group_name"`
	CountryCode     pgtype.Text        `json:"country_code"`
	Version         string             `json:"version"`
	Status          string             `json:"status"`
	RecordCount     int32              `json:"record_count"`
	PrimaryFormat   string             `json:"primary_format"`
	Formats         []string           `json:"formats"`
	SchemaPath      pgtype.Text        `json:"schema_path"`
	LicenceID       pgtype.Text        `json:"licence_id"`
	SourceCount     int32              `json:"source_count"`
	UpdateFrequency pgtype.Text        `json:"update_frequency"`
	LastUpdatedAt   pgtype.Date        `json:"last_updated_at"`
	LastVerifiedAt  pgtype.Date        `json:"last_verified_at"`
	Maintainers     []string           `json:"maintainers"`
	IsPublic        bool               `json:"is_public"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
}

type DatasetSource struct {
	ID             pgtype.UUID        `json:"id"`
	DatasetID      pgtype.UUID        `json:"dataset_id"`
	SourceKey      string             `json:"source_key"`
	Name           string             `json:"name"`
	Url            pgtype.Text        `json:"url"`
	Description    pgtype.Text        `json:"description"`
	Publisher      pgtype.Text        `json:"publisher"`
	SourceType     pgtype.Text        `json:"source_type"`
	LicenceID      pgtype.Text        `json:"licence_id"`
	IsOfficial     bool               `json:"is_official"`
	LastFetchedAt  pgtype.Timestamptz `json:"last_fetched_at"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DatasetVersion struct {
	ID            pgtype.UUID        `json:"id"`
	DatasetID     pgtype.UUID        `json:"dataset_id"`
	Version       string             `json:"version"`
	SchemaVersion pgtype.Text        `json:"schema_version"`
	Format        string             `json:"format"`
	Status        string             `json:"status"`
	RecordCount   int32              `json:"record_count"`
	Checksum      pgtype.Text        `json:"checksum"`
	StoragePath   pgtype.Text        `json:"storage_path"`
	Notes         pgtype.Text        `json:"notes"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	AccessTokenJti   pgtype.UUID        `json:"access_token_jti"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UsageDaily struct {
	ID                   int64              `json:"id"`
	UsageDate            pgtype.Date        `json:"usage_date"`
	ScopeType            string             `json:"scope_type"`
	AccountID            pgtype.UUID        `json:"account_id"`
	ApiKeyID             pgtype.UUID        `json:"api_key_id"`
	AnonymousID          pgtype.UUID        `json:"anonymous_id"`
	RequestCount         int32              `json:"request_count"`
	SuccessfulCount      int32              `json:"successful_count"`
	ErrorCount           int32              `json:"error_count"`
	DatasetDownloadCount int32              `json:"dataset_download_count"`
	ResponseBytes        int64              `json:"response_bytes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
