// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveDataset(ctx context.Context, id pgtype.UUID) (Dataset, error)
	CountActiveAPIKeysByAccountID(ctx context.Context, accountID pgtype.UUID) (int64, error)
	CountRequestsByRoute(ctx context.Context, arg CountRequestsByRouteParams) (int64, error)
	// API keys queries
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// Accounts queries
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Dataset queries
	CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error)
	CreateDatasetSource(ctx context.Context, arg CreateDatasetSourceParams) (DatasetSource, error)
	CreateDatasetVersion(ctx context.Context, arg CreateDatasetVersionParams) (DatasetVersion, error)
	// Sessions queries
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteDatasetSource(ctx context.Context, id pgtype.UUID) error
	DeleteDatasetVersion(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredAPIKeys(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredUsageDaily(ctx context.Context, usageDate pgtype.Date) error
	DeleteSessionsByAccountID(ctx context.Context, accountID pgtype.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetAccountByEmail(ctx context.Context, lower string) (Account, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByUsername(ctx context.Context, lower string) (Account, error)
	GetDatasetByID(ctx context.Context, id pgtype.UUID) (Dataset, error)
	GetDatasetByKey(ctx context.Context, lower string) (Dataset, error)
	GetDatasetBySlug(ctx context.Context, lower string) (Dataset, error)
	GetDatasetSourceByID(ctx context.Context, id pgtype.UUID) (DatasetSource, error)
	GetDatasetVersionByDatasetAndVersion(ctx context.Context, arg GetDatasetVersionByDatasetAndVersionParams) (DatasetVersion, error)
	GetDatasetVersionByID(ctx context.Context, id pgtype.UUID) (DatasetVersion, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetUsageDailyByDate(ctx context.Context, usageDate pgtype.Date) ([]UsageDaily, error)
	GetUsageSummaryByAPIKeyID(ctx context.Context, arg GetUsageSummaryByAPIKeyIDParams) ([]GetUsageSummaryByAPIKeyIDRow, error)
	GetUsageSummaryByAccountID(ctx context.Context, arg GetUsageSummaryByAccountIDParams) ([]GetUsageSummaryByAccountIDRow, error)
	GetUsageSummaryByAnonymousID(ctx context.Context, arg GetUsageSummaryByAnonymousIDParams) ([]GetUsageSummaryByAnonymousIDRow, error)
	InsertAPIRequestLog(ctx context.Context, arg InsertAPIRequestLogParams) (ApiRequest, error)
	ListAPIKeysByAccountID(ctx context.Context, arg ListAPIKeysByAccountIDParams) ([]ApiKey, error)
	ListAPIKeysByAccountIDAfter(ctx context.Context, arg ListAPIKeysByAccountIDAfterParams) ([]ApiKey, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListAccountsAfter(ctx context.Context, arg ListAccountsAfterParams) ([]Account, error)
	ListAllDatasets(ctx context.Context, arg ListAllDatasetsParams) ([]Dataset, error)
	ListAllDatasetsAfter(ctx context.Context, arg ListAllDatasetsAfterParams) ([]Dataset, error)
	ListDatasetSources(ctx context.Context, datasetID pgtype.UUID) ([]DatasetSource, error)
	ListDatasetVersions(ctx context.Context, datasetID pgtype.UUID) ([]DatasetVersion, error)
	ListPublicDatasets(ctx context.Context, arg ListPublicDatasetsParams) ([]Dataset, error)
	ListPublicDatasetsAfter(ctx context.Context, arg ListPublicDatasetsAfterParams) ([]Dataset, error)
	ListPublicDatasetsByGroup(ctx context.Context, arg ListPublicDatasetsByGroupParams) ([]Dataset, error)
	ListPublicDatasetsByGroupAfter(ctx context.Context, arg ListPublicDatasetsByGroupAfterParams) ([]Dataset, error)
	ListPublicDatasetsByGroupAndStatus(ctx context.Context, arg ListPublicDatasetsByGroupAndStatusParams) ([]Dataset, error)
	ListPublicDatasetsByGroupAndStatusAfter(ctx context.Context, arg ListPublicDatasetsByGroupAndStatusAfterParams) ([]Dataset, error)
	ListPublicDatasetsByStatus(ctx context.Context, arg ListPublicDatasetsByStatusParams) ([]Dataset, error)
	ListPublicDatasetsByStatusAfter(ctx context.Context, arg ListPublicDatasetsByStatusAfterParams) ([]Dataset, error)
	ListSessionsByAccountID(ctx context.Context, arg ListSessionsByAccountIDParams) ([]Session, error)
	ListSessionsByAccountIDAfter(ctx context.Context, arg ListSessionsByAccountIDAfterParams) ([]Session, error)
	MarkAccountLogin(ctx context.Context, id pgtype.UUID) (Account, error)
	PublishDatasetVersion(ctx context.Context, id pgtype.UUID) (DatasetVersion, error)
	RevokeAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	RevokeSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	RevokeSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	RotateAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	SoftDeleteAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	TouchAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	TouchSession(ctx context.Context, id pgtype.UUID) (Session, error)
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (Account, error)
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (Account, error)
	UpdateDatasetMetadata(ctx context.Context, arg UpdateDatasetMetadataParams) (Dataset, error)
	UpdateDatasetSource(ctx context.Context, arg UpdateDatasetSourceParams) (DatasetSource, error)
	UpdateDatasetVersion(ctx context.Context, arg UpdateDatasetVersionParams) (DatasetVersion, error)
	UpsertAPIKeyUsageDaily(ctx context.Context, arg UpsertAPIKeyUsageDailyParams) error
	UpsertAccountUsageDaily(ctx context.Context, arg UpsertAccountUsageDailyParams) error
	// Usage queries
	UpsertAnonymousUsageDaily(ctx context.Context, arg UpsertAnonymousUsageDailyParams) error
	VerifyAccountEmail(ctx context.Context, id pgtype.UUID) (Account, error)
}

var _ Querier = (*Queries)(nil)
