// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (
    account_id,
    refresh_token_hash,
    access_token_jti,
    user_agent,
    ip_address,
    expires_at,
    revoked_at,
    last_used_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type CreateSessionParams struct {
	AccountID        pgtype.UUID        `json:"account_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	AccessTokenJti   pgtype.UUID        `json:"access_token_jti"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

// Sessions queries
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.RefreshTokenHash,
		arg.AccessTokenJti,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.LastUsedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.AccessTokenJti,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
   OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionsByAccountID = `-- name: DeleteSessionsByAccountID :exec
DELETE FROM sessions
WHERE account_id = $1
`

func (q *Queries) DeleteSessionsByAccountID(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByAccountID, accountID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.AccessTokenJti,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
FROM sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.AccessTokenJti,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByAccountID = `-- name: ListSessionsByAccountID :many
SELECT id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
FROM sessions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSessionsByAccountIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListSessionsByAccountID(ctx context.Context, arg ListSessionsByAccountIDParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RefreshTokenHash,
			&i.AccessTokenJti,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByAccountIDAfter = `-- name: ListSessionsByAccountIDAfter :many
SELECT id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
FROM sessions
WHERE account_id = $1
  AND (
    created_at < $3
    OR (created_at = $3 AND id < $4)
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListSessionsByAccountIDAfterParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Limit     int32              `json:"limit"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) ListSessionsByAccountIDAfter(ctx context.Context, arg ListSessionsByAccountIDAfterParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAccountIDAfter,
		arg.AccountID,
		arg.Limit,
		arg.CreatedAt,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RefreshTokenHash,
			&i.AccessTokenJti,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessionByID = `-- name: RevokeSessionByID :one
UPDATE sessions
SET
    revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.AccessTokenJti,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionByRefreshTokenHash = `-- name: RevokeSessionByRefreshTokenHash :one
UPDATE sessions
SET
    revoked_at = now(),
    updated_at = now()
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
RETURNING id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
`

func (q *Queries) RevokeSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.AccessTokenJti,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET
    last_used_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, account_id, refresh_token_hash, access_token_jti, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at, updated_at
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshTokenHash,
		&i.AccessTokenJti,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
