// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: usage.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRequestsByRoute = `-- name: CountRequestsByRoute :one
SELECT COUNT(*)::bigint AS request_count
FROM api_requests
WHERE route = $1
  AND created_at >= $2
  AND created_at < $3
`

type CountRequestsByRouteParams struct {
	Route       pgtype.Text        `json:"route"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountRequestsByRoute(ctx context.Context, arg CountRequestsByRouteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByRoute, arg.Route, arg.CreatedAt, arg.CreatedAt_2)
	var request_count int64
	err := row.Scan(&request_count)
	return request_count, err
}

const deleteExpiredUsageDaily = `-- name: DeleteExpiredUsageDaily :exec
DELETE FROM usage_daily
WHERE usage_date < $1
`

func (q *Queries) DeleteExpiredUsageDaily(ctx context.Context, usageDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteExpiredUsageDaily, usageDate)
	return err
}

const getUsageDailyByDate = `-- name: GetUsageDailyByDate :many
SELECT id, usage_date, scope_type, account_id, api_key_id, anonymous_id, request_count, successful_count, error_count, dataset_download_count, response_bytes, created_at, updated_at
FROM usage_daily
WHERE usage_date = $1
ORDER BY scope_type, account_id, api_key_id, anonymous_id
`

func (q *Queries) GetUsageDailyByDate(ctx context.Context, usageDate pgtype.Date) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, getUsageDailyByDate, usageDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageDaily{}
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.ID,
			&i.UsageDate,
			&i.ScopeType,
			&i.AccountID,
			&i.ApiKeyID,
			&i.AnonymousID,
			&i.RequestCount,
			&i.SuccessfulCount,
			&i.ErrorCount,
			&i.DatasetDownloadCount,
			&i.ResponseBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummaryByAPIKeyID = `-- name: GetUsageSummaryByAPIKeyID :many
SELECT
    usage_date,
    request_count,
    successful_count,
    error_count,
    dataset_download_count,
    response_bytes
FROM usage_daily
WHERE api_key_id = $1
ORDER BY usage_date DESC
LIMIT $2 OFFSET $3
`

type GetUsageSummaryByAPIKeyIDParams struct {
	ApiKeyID pgtype.UUID `json:"api_key_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetUsageSummaryByAPIKeyIDRow struct {
	UsageDate            pgtype.Date `json:"usage_date"`
	RequestCount         int32       `json:"request_count"`
	SuccessfulCount      int32       `json:"successful_count"`
	ErrorCount           int32       `json:"error_count"`
	DatasetDownloadCount int32       `json:"dataset_download_count"`
	ResponseBytes        int64       `json:"response_bytes"`
}

func (q *Queries) GetUsageSummaryByAPIKeyID(ctx context.Context, arg GetUsageSummaryByAPIKeyIDParams) ([]GetUsageSummaryByAPIKeyIDRow, error) {
	rows, err := q.db.Query(ctx, getUsageSummaryByAPIKeyID, arg.ApiKeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageSummaryByAPIKeyIDRow{}
	for rows.Next() {
		var i GetUsageSummaryByAPIKeyIDRow
		if err := rows.Scan(
			&i.UsageDate,
			&i.RequestCount,
			&i.SuccessfulCount,
			&i.ErrorCount,
			&i.DatasetDownloadCount,
			&i.ResponseBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummaryByAccountID = `-- name: GetUsageSummaryByAccountID :many
SELECT
    usage_date,
    request_count,
    successful_count,
    error_count,
    dataset_download_count,
    response_bytes
FROM usage_daily
WHERE account_id = $1
ORDER BY usage_date DESC
LIMIT $2 OFFSET $3
`

type GetUsageSummaryByAccountIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type GetUsageSummaryByAccountIDRow struct {
	UsageDate            pgtype.Date `json:"usage_date"`
	RequestCount         int32       `json:"request_count"`
	SuccessfulCount      int32       `json:"successful_count"`
	ErrorCount           int32       `json:"error_count"`
	DatasetDownloadCount int32       `json:"dataset_download_count"`
	ResponseBytes        int64       `json:"response_bytes"`
}

func (q *Queries) GetUsageSummaryByAccountID(ctx context.Context, arg GetUsageSummaryByAccountIDParams) ([]GetUsageSummaryByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getUsageSummaryByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageSummaryByAccountIDRow{}
	for rows.Next() {
		var i GetUsageSummaryByAccountIDRow
		if err := rows.Scan(
			&i.UsageDate,
			&i.RequestCount,
			&i.SuccessfulCount,
			&i.ErrorCount,
			&i.DatasetDownloadCount,
			&i.ResponseBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummaryByAnonymousID = `-- name: GetUsageSummaryByAnonymousID :many
SELECT
    usage_date,
    request_count,
    successful_count,
    error_count,
    dataset_download_count,
    response_bytes
FROM usage_daily
WHERE anonymous_id = $1
ORDER BY usage_date DESC
LIMIT $2 OFFSET $3
`

type GetUsageSummaryByAnonymousIDParams struct {
	AnonymousID pgtype.UUID `json:"anonymous_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type GetUsageSummaryByAnonymousIDRow struct {
	UsageDate            pgtype.Date `json:"usage_date"`
	RequestCount         int32       `json:"request_count"`
	SuccessfulCount      int32       `json:"successful_count"`
	ErrorCount           int32       `json:"error_count"`
	DatasetDownloadCount int32       `json:"dataset_download_count"`
	ResponseBytes        int64       `json:"response_bytes"`
}

func (q *Queries) GetUsageSummaryByAnonymousID(ctx context.Context, arg GetUsageSummaryByAnonymousIDParams) ([]GetUsageSummaryByAnonymousIDRow, error) {
	rows, err := q.db.Query(ctx, getUsageSummaryByAnonymousID, arg.AnonymousID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageSummaryByAnonymousIDRow{}
	for rows.Next() {
		var i GetUsageSummaryByAnonymousIDRow
		if err := rows.Scan(
			&i.UsageDate,
			&i.RequestCount,
			&i.SuccessfulCount,
			&i.ErrorCount,
			&i.DatasetDownloadCount,
			&i.ResponseBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAPIRequestLog = `-- name: InsertAPIRequestLog :one
INSERT INTO api_requests (
    request_id,
    account_id,
    api_key_id,
    anonymous_id,
    method,
    path,
    route,
    query_params,
    status_code,
    ip_address,
    user_agent,
    response_time_ms,
    request_bytes,
    response_bytes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    COALESCE($8, '{}'::jsonb),
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, request_id, account_id, api_key_id, anonymous_id, method, path, route, query_params, status_code, ip_address, user_agent, response_time_ms, request_bytes, response_bytes, created_at
`

type InsertAPIRequestLogParams struct {
	RequestID      string      `json:"request_id"`
	AccountID      pgtype.UUID `json:"account_id"`
	ApiKeyID       pgtype.UUID `json:"api_key_id"`
	AnonymousID    pgtype.UUID `json:"anonymous_id"`
	Method         string      `json:"method"`
	Path           string      `json:"path"`
	Route          pgtype.Text `json:"route"`
	Column8        interface{} `json:"column_8"`
	StatusCode     int32       `json:"status_code"`
	IpAddress      *netip.Addr `json:"ip_address"`
	UserAgent      pgtype.Text `json:"user_agent"`
	ResponseTimeMs pgtype.Int4 `json:"response_time_ms"`
	RequestBytes   pgtype.Int8 `json:"request_bytes"`
	ResponseBytes  pgtype.Int8 `json:"response_bytes"`
}

func (q *Queries) InsertAPIRequestLog(ctx context.Context, arg InsertAPIRequestLogParams) (ApiRequest, error) {
	row := q.db.QueryRow(ctx, insertAPIRequestLog,
		arg.RequestID,
		arg.AccountID,
		arg.ApiKeyID,
		arg.AnonymousID,
		arg.Method,
		arg.Path,
		arg.Route,
		arg.Column8,
		arg.StatusCode,
		arg.IpAddress,
		arg.UserAgent,
		arg.ResponseTimeMs,
		arg.RequestBytes,
		arg.ResponseBytes,
	)
	var i ApiRequest
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.AccountID,
		&i.ApiKeyID,
		&i.AnonymousID,
		&i.Method,
		&i.Path,
		&i.Route,
		&i.QueryParams,
		&i.StatusCode,
		&i.IpAddress,
		&i.UserAgent,
		&i.ResponseTimeMs,
		&i.RequestBytes,
		&i.ResponseBytes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAPIKeyUsageDaily = `-- name: UpsertAPIKeyUsageDaily :exec
INSERT INTO usage_daily (
    usage_date,
    scope_type,
    api_key_id,
    request_count,
    successful_count,
    error_count,
    dataset_download_count,
    response_bytes
)
SELECT
    $1,
    'api_key',
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
ON CONFLICT (usage_date, api_key_id) WHERE scope_type = 'api_key'
DO UPDATE SET
    request_count = usage_daily.request_count + EXCLUDED.request_count,
    successful_count = usage_daily.successful_count + EXCLUDED.successful_count,
    error_count = usage_daily.error_count + EXCLUDED.error_count,
    dataset_download_count = usage_daily.dataset_download_count + EXCLUDED.dataset_download_count,
    response_bytes = usage_daily.response_bytes + EXCLUDED.response_bytes,
    updated_at = now()
`

type UpsertAPIKeyUsageDailyParams struct {
	UsageDate            pgtype.Date `json:"usage_date"`
	ApiKeyID             pgtype.UUID `json:"api_key_id"`
	RequestCount         int32       `json:"request_count"`
	SuccessfulCount      int32       `json:"successful_count"`
	ErrorCount           int32       `json:"error_count"`
	DatasetDownloadCount int32       `json:"dataset_download_count"`
	ResponseBytes        int64       `json:"response_bytes"`
}

func (q *Queries) UpsertAPIKeyUsageDaily(ctx context.Context, arg UpsertAPIKeyUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertAPIKeyUsageDaily,
		arg.UsageDate,
		arg.ApiKeyID,
		arg.RequestCount,
		arg.SuccessfulCount,
		arg.ErrorCount,
		arg.DatasetDownloadCount,
		arg.ResponseBytes,
	)
	return err
}

const upsertAccountUsageDaily = `-- name: UpsertAccountUsageDaily :exec
INSERT INTO usage_daily (
    usage_date,
    scope_type,
    account_id,
    request_count,
    successful_count,
    error_count,
    dataset_download_count,
    response_bytes
)
SELECT
    $1,
    'account',
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
ON CONFLICT (usage_date, account_id) WHERE scope_type = 'account'
DO UPDATE SET
    request_count = usage_daily.request_count + EXCLUDED.request_count,
    successful_count = usage_daily.successful_count + EXCLUDED.successful_count,
    error_count = usage_daily.error_count + EXCLUDED.error_count,
    dataset_download_count = usage_daily.dataset_download_count + EXCLUDED.dataset_download_count,
    response_bytes = usage_daily.response_bytes + EXCLUDED.response_bytes,
    updated_at = now()
`

type UpsertAccountUsageDailyParams struct {
	UsageDate            pgtype.Date `json:"usage_date"`
	AccountID            pgtype.UUID `json:"account_id"`
	RequestCount         int32       `json:"request_count"`
	SuccessfulCount      int32       `json:"successful_count"`
	ErrorCount           int32       `json:"error_count"`
	DatasetDownloadCount int32       `json:"dataset_download_count"`
	ResponseBytes        int64       `json:"response_bytes"`
}

func (q *Queries) UpsertAccountUsageDaily(ctx context.Context, arg UpsertAccountUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertAccountUsageDaily,
		arg.UsageDate,
		arg.AccountID,
		arg.RequestCount,
		arg.SuccessfulCount,
		arg.ErrorCount,
		arg.DatasetDownloadCount,
		arg.ResponseBytes,
	)
	return err
}

const upsertAnonymousUsageDaily = `-- name: UpsertAnonymousUsageDaily :exec

INSERT INTO usage_daily (
    usage_date,
    scope_type,
    anonymous_id,
    request_count,
    successful_count,
    error_count,
    dataset_download_count,
    response_bytes
)
SELECT
    $1,
    'anonymous',
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
ON CONFLICT (usage_date, anonymous_id) WHERE scope_type = 'anonymous'
DO UPDATE SET
    request_count = usage_daily.request_count + EXCLUDED.request_count,
    successful_count = usage_daily.successful_count + EXCLUDED.successful_count,
    error_count = usage_daily.error_count + EXCLUDED.error_count,
    dataset_download_count = usage_daily.dataset_download_count + EXCLUDED.dataset_download_count,
    response_bytes = usage_daily.response_bytes + EXCLUDED.response_bytes,
    updated_at = now()
`

type UpsertAnonymousUsageDailyParams struct {
	UsageDate            pgtype.Date `json:"usage_date"`
	AnonymousID          pgtype.UUID `json:"anonymous_id"`
	RequestCount         int32       `json:"request_count"`
	SuccessfulCount      int32       `json:"successful_count"`
	ErrorCount           int32       `json:"error_count"`
	DatasetDownloadCount int32       `json:"dataset_download_count"`
	ResponseBytes        int64       `json:"response_bytes"`
}

// Usage queries
func (q *Queries) UpsertAnonymousUsageDaily(ctx context.Context, arg UpsertAnonymousUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertAnonymousUsageDaily,
		arg.UsageDate,
		arg.AnonymousID,
		arg.RequestCount,
		arg.SuccessfulCount,
		arg.ErrorCount,
		arg.DatasetDownloadCount,
		arg.ResponseBytes,
	)
	return err
}
